### ISSUE TITLE
406 Client Error: Not Acceptable

### ISSUE THREAD

**Issue by felipe-vvoosh** [dpavlos/elasticsearch_migration#1]
Hi, I tried to use your script and I got this error...

I'm trying to migrate from 1.7.6 to 6.3.1...

Can you help?

Thanks

**Comment by felipe-vvoosh** [comment]
It seems to be related to the post not having a header setting the content type to json... It works if you do that :)... Thanks!

**Comment by dpavlos** [comment]
Hi @felipe-vvoosh ,

thanks for your comment! Yes indeed, on Elasticsearch v5.x content type is optional (false by default) and the server does automatic detection (defaults to json). This is not the case for v6.x though, where all REST requests must provide the correct content type ( see: https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests ).
